//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railworker.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Railworker.Language.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to rules.
        /// </summary>
        public static string add_to_rules {
            get {
                return ResourceManager.GetString("add_to_rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string asfdsdfads {
            get {
                return ResourceManager.GetString("asfdsdfads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic information.
        /// </summary>
        public static string basic_information {
            get {
                return ResourceManager.GetString("basic_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string browse {
            get {
                return ResourceManager.GetString("browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change number.
        /// </summary>
        public static string change_number {
            get {
                return ResourceManager.GetString("change_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child object.
        /// </summary>
        public static string child_object {
            get {
                return ResourceManager.GetString("child_object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child objects.
        /// </summary>
        public static string child_objects {
            get {
                return ResourceManager.GetString("child_objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose directory.
        /// </summary>
        public static string choose_directory {
            get {
                return ResourceManager.GetString("choose_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consists.
        /// </summary>
        public static string consists {
            get {
                return ResourceManager.GetString("consists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container components.
        /// </summary>
        public static string container_components {
            get {
                return ResourceManager.GetString("container_components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control value name.
        /// </summary>
        public static string control_value_name {
            get {
                return ResourceManager.GetString("control_value_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control values.
        /// </summary>
        public static string control_values {
            get {
                return ResourceManager.GetString("control_values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create vehicle variation.
        /// </summary>
        public static string create_vehicle_variation {
            get {
                return ResourceManager.GetString("create_vehicle_variation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string create_vehicle_variationfds {
            get {
                return ResourceManager.GetString("create_vehicle_variationfds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default value.
        /// </summary>
        public static string default_value {
            get {
                return ResourceManager.GetString("default_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        public static string directory {
            get {
                return ResourceManager.GetString("directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string dsfa {
            get {
                return ResourceManager.GetString("dsfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit scenario.
        /// </summary>
        public static string edit_scenario {
            get {
                return ResourceManager.GetString("edit_scenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string enable {
            get {
                return ResourceManager.GetString("enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string enabled {
            get {
                return ResourceManager.GetString("enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase.
        /// </summary>
        public static string erase {
            get {
                return ResourceManager.GetString("erase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string export {
            get {
                return ResourceManager.GetString("export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read file.
        /// </summary>
        public static string failed_to_read_file {
            get {
                return ResourceManager.GetString("failed_to_read_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist.
        /// </summary>
        public static string file_does_not_exist {
            get {
                return ResourceManager.GetString("file_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        public static string filename {
            get {
                return ResourceManager.GetString("filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid.
        /// </summary>
        public static string guid {
            get {
                return ResourceManager.GetString("guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert above.
        /// </summary>
        public static string insert_above {
            get {
                return ResourceManager.GetString("insert_above", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert below.
        /// </summary>
        public static string insert_below {
            get {
                return ResourceManager.GetString("insert_below", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverted.
        /// </summary>
        public static string inverted {
            get {
                return ResourceManager.GetString("inverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading routes.
        /// </summary>
        public static string loading_routes {
            get {
                return ResourceManager.GetString("loading_routes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading scenarios.
        /// </summary>
        public static string loading_scenarios {
            get {
                return ResourceManager.GetString("loading_scenarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum value.
        /// </summary>
        public static string maximum_value {
            get {
                return ResourceManager.GetString("maximum_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum value.
        /// </summary>
        public static string minimum_value {
            get {
                return ResourceManager.GetString("minimum_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string msg_error {
            get {
                return ResourceManager.GetString("msg_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your Train Simulator directory.
        /// </summary>
        public static string msg_first_time {
            get {
                return ResourceManager.GetString("msg_first_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string msg_message {
            get {
                return ResourceManager.GetString("msg_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected path is invalid! (Check if it contains RailWorks.exe).
        /// </summary>
        public static string msg_ts_path_invalid {
            get {
                return ResourceManager.GetString("msg_ts_path_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid TS path is required to run this application. The application will now exit..
        /// </summary>
        public static string msg_ts_path_required {
            get {
                return ResourceManager.GetString("msg_ts_path_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string msg_warning {
            get {
                return ResourceManager.GetString("msg_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement vehicle.
        /// </summary>
        public static string new_vehicle {
            get {
                return ResourceManager.GetString("new_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string not_found {
            get {
                return ResourceManager.GetString("not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number list.
        /// </summary>
        public static string number_list {
            get {
                return ResourceManager.GetString("number_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old vehicle.
        /// </summary>
        public static string old_vehicle {
            get {
                return ResourceManager.GetString("old_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file.
        /// </summary>
        public static string open_file {
            get {
                return ResourceManager.GetString("open_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open scenario directory.
        /// </summary>
        public static string open_scenario_directory {
            get {
                return ResourceManager.GetString("open_scenario_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string path {
            get {
                return ResourceManager.GetString("path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Tracks.bin.
        /// </summary>
        public static string process_track_bin {
            get {
                return ResourceManager.GetString("process_track_bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Tracks.bin.
        /// </summary>
        public static string process_tracks_bin {
            get {
                return ResourceManager.GetString("process_tracks_bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Tracks.bin.
        /// </summary>
        public static string processing_tracks_bin {
            get {
                return ResourceManager.GetString("processing_tracks_bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading scenario files.
        /// </summary>
        public static string reading_scenario_files {
            get {
                return ResourceManager.GetString("reading_scenario_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string replace {
            get {
                return ResourceManager.GetString("replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace all.
        /// </summary>
        public static string replace_all {
            get {
                return ResourceManager.GetString("replace_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with.
        /// </summary>
        public static string replace_with {
            get {
                return ResourceManager.GetString("replace_with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolling stock.
        /// </summary>
        public static string rolling_stock {
            get {
                return ResourceManager.GetString("rolling_stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolling stock replacement.
        /// </summary>
        public static string rolling_stock_replacement {
            get {
                return ResourceManager.GetString("rolling_stock_replacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route.
        /// </summary>
        public static string route {
            get {
                return ResourceManager.GetString("route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route Visualizer.
        /// </summary>
        public static string route_visualizer {
            get {
                return ResourceManager.GetString("route_visualizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routes.
        /// </summary>
        public static string routes {
            get {
                return ResourceManager.GetString("routes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routes and scenarios.
        /// </summary>
        public static string routes_and_scenarios {
            get {
                return ResourceManager.GetString("routes_and_scenarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show list.
        /// </summary>
        public static string routes_show_list {
            get {
                return ResourceManager.GetString("routes_show_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        public static string save_as {
            get {
                return ResourceManager.GetString("save_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save copy.
        /// </summary>
        public static string save_copy {
            get {
                return ResourceManager.GetString("save_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file.
        /// </summary>
        public static string save_file {
            get {
                return ResourceManager.GetString("save_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning .bin files.
        /// </summary>
        public static string scanning_bin_files {
            get {
                return ResourceManager.GetString("scanning_bin_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario.
        /// </summary>
        public static string scenario {
            get {
                return ResourceManager.GetString("scenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenarios.
        /// </summary>
        public static string scenarios {
            get {
                return ResourceManager.GetString("scenarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View scenario list.
        /// </summary>
        public static string scenarios_show_list {
            get {
                return ResourceManager.GetString("scenarios_show_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script.
        /// </summary>
        public static string script {
            get {
                return ResourceManager.GetString("script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script component.
        /// </summary>
        public static string script_component {
            get {
                return ResourceManager.GetString("script_component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search vehicles.
        /// </summary>
        public static string search_vehicles {
            get {
                return ResourceManager.GetString("search_vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Train Simulator directory.
        /// </summary>
        public static string select_ts_path {
            get {
                return ResourceManager.GetString("select_ts_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to serz.exe path.
        /// </summary>
        public static string serz_exe_path {
            get {
                return ResourceManager.GetString("serz_exe_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested display name:.
        /// </summary>
        public static string suggested_display_name {
            get {
                return ResourceManager.GetString("suggested_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested filename:.
        /// </summary>
        public static string suggested_filename {
            get {
                return ResourceManager.GetString("suggested_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string test2 {
            get {
                return ResourceManager.GetString("test2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string test3 {
            get {
                return ResourceManager.GetString("test3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TS path.
        /// </summary>
        public static string ts_path {
            get {
                return ResourceManager.GetString("ts_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn around.
        /// </summary>
        public static string turn_around_vehicle {
            get {
                return ResourceManager.GetString("turn_around_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown name.
        /// </summary>
        public static string unknown_name {
            get {
                return ResourceManager.GetString("unknown_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use system language.
        /// </summary>
        public static string use_system_language {
            get {
                return ResourceManager.GetString("use_system_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naming hints: ND means &quot;No Driver&quot;, KI (german for AI) is for non player trains, ST is for &quot;Static&quot; vehicles. It&apos;s good practise to prefix your [Author] name in brackets. Example: [Author] Locomotive KI ND.
        /// </summary>
        public static string vehicle_naming_conventions {
            get {
                return ResourceManager.GetString("vehicle_naming_conventions", resourceCulture);
            }
        }
    }
}
