//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railworker.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Railworker.Language.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protected.
        /// </summary>
        public static string _protected {
            get {
                return ResourceManager.GetString("protected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add as preload consist.
        /// </summary>
        public static string add_as_preload_consist {
            get {
                return ResourceManager.GetString("add_as_preload_consist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        public static string add_new {
            get {
                return ResourceManager.GetString("add_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to rules.
        /// </summary>
        public static string add_to_rules {
            get {
                return ResourceManager.GetString("add_to_rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        public static string always {
            get {
                return ResourceManager.GetString("always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string asfdsdfads {
            get {
                return ResourceManager.GetString("asfdsdfads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string author {
            get {
                return ResourceManager.GetString("author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic information.
        /// </summary>
        public static string basic_information {
            get {
                return ResourceManager.GetString("basic_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string browse {
            get {
                return ResourceManager.GetString("browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change number.
        /// </summary>
        public static string change_number {
            get {
                return ResourceManager.GetString("change_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child object.
        /// </summary>
        public static string child_object {
            get {
                return ResourceManager.GetString("child_object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child objects.
        /// </summary>
        public static string child_objects {
            get {
                return ResourceManager.GetString("child_objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose directory.
        /// </summary>
        public static string choose_directory {
            get {
                return ResourceManager.GetString("choose_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear assets.
        /// </summary>
        public static string clear_assets {
            get {
                return ResourceManager.GetString("clear_assets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composition editor.
        /// </summary>
        public static string composition_editor {
            get {
                return ResourceManager.GetString("composition_editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compositions.
        /// </summary>
        public static string compositions {
            get {
                return ResourceManager.GetString("compositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consists.
        /// </summary>
        public static string consists {
            get {
                return ResourceManager.GetString("consists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container components.
        /// </summary>
        public static string container_components {
            get {
                return ResourceManager.GetString("container_components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control value name.
        /// </summary>
        public static string control_value_name {
            get {
                return ResourceManager.GetString("control_value_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control values.
        /// </summary>
        public static string control_values {
            get {
                return ResourceManager.GetString("control_values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRAN.
        /// </summary>
        public static string cran {
            get {
                return ResourceManager.GetString("cran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRAN addon edit.
        /// </summary>
        public static string cran_addon_edit {
            get {
                return ResourceManager.GetString("cran_addon_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRAN addons.
        /// </summary>
        public static string cran_addons_page {
            get {
                return ResourceManager.GetString("cran_addons_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRAN admin.
        /// </summary>
        public static string cran_admin {
            get {
                return ResourceManager.GetString("cran_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRAN new addon.
        /// </summary>
        public static string cran_new_addon {
            get {
                return ResourceManager.GetString("cran_new_addon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create vehicle variation.
        /// </summary>
        public static string create_vehicle_variation {
            get {
                return ResourceManager.GetString("create_vehicle_variation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string create_vehicle_variationfds {
            get {
                return ResourceManager.GetString("create_vehicle_variationfds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default value.
        /// </summary>
        public static string default_value {
            get {
                return ResourceManager.GetString("default_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selected.
        /// </summary>
        public static string delete_selected {
            get {
                return ResourceManager.GetString("delete_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        public static string directory {
            get {
                return ResourceManager.GetString("directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do for all.
        /// </summary>
        public static string do_for_all {
            get {
                return ResourceManager.GetString("do_for_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string download {
            get {
                return ResourceManager.GetString("download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We found different driving charactersitics for &quot;{0}&quot;. Do you wish to keep the custom &quot;{0}&quot;? from the repaint?.
        /// </summary>
        public static string driving_characteristics_mismatch {
            get {
                return ResourceManager.GetString("driving_characteristics_mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string dsfa {
            get {
                return ResourceManager.GetString("dsfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit scenario.
        /// </summary>
        public static string edit_scenario {
            get {
                return ResourceManager.GetString("edit_scenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit selected.
        /// </summary>
        public static string edit_selected {
            get {
                return ResourceManager.GetString("edit_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string enable {
            get {
                return ResourceManager.GetString("enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string enabled {
            get {
                return ResourceManager.GetString("enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase.
        /// </summary>
        public static string erase {
            get {
                return ResourceManager.GetString("erase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string export {
            get {
                return ResourceManager.GetString("export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read file.
        /// </summary>
        public static string failed_to_read_file {
            get {
                return ResourceManager.GetString("failed_to_read_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string fdafdsafa {
            get {
                return ResourceManager.GetString("fdafdsafa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists.
        /// </summary>
        public static string file_already_exists {
            get {
                return ResourceManager.GetString("file_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist.
        /// </summary>
        public static string file_does_not_exist {
            get {
                return ResourceManager.GetString("file_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extensions to ignore.
        /// </summary>
        public static string file_extensions_to_ignore {
            get {
                return ResourceManager.GetString("file_extensions_to_ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        public static string filename {
            get {
                return ResourceManager.GetString("filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string find {
            get {
                return ResourceManager.GetString("find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find repaints.
        /// </summary>
        public static string find_repaints {
            get {
                return ResourceManager.GetString("find_repaints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics.
        /// </summary>
        public static string graphics {
            get {
                return ResourceManager.GetString("graphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid.
        /// </summary>
        public static string guid {
            get {
                return ResourceManager.GetString("guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert above.
        /// </summary>
        public static string insert_above {
            get {
                return ResourceManager.GetString("insert_above", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert below.
        /// </summary>
        public static string insert_below {
            get {
                return ResourceManager.GetString("insert_below", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspector.
        /// </summary>
        public static string inspector {
            get {
                return ResourceManager.GetString("inspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string install {
            get {
                return ResourceManager.GetString("install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverted.
        /// </summary>
        public static string inverted {
            get {
                return ResourceManager.GetString("inverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep.
        /// </summary>
        public static string keep {
            get {
                return ResourceManager.GetString("keep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We found a different driver position in the repaint. Do you want to keep the custom driver position?.
        /// </summary>
        public static string keep_driver_position {
            get {
                return ResourceManager.GetString("keep_driver_position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep maximum speed.
        /// </summary>
        public static string keep_max_speed {
            get {
                return ResourceManager.GetString("keep_max_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to keep the custom numbering list from the repaint?.
        /// </summary>
        public static string keep_numbering_list {
            get {
                return ResourceManager.GetString("keep_numbering_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string license {
            get {
                return ResourceManager.GetString("license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading authors.
        /// </summary>
        public static string loading_authors {
            get {
                return ResourceManager.GetString("loading_authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading routes.
        /// </summary>
        public static string loading_routes {
            get {
                return ResourceManager.GetString("loading_routes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading scenarios.
        /// </summary>
        public static string loading_scenarios {
            get {
                return ResourceManager.GetString("loading_scenarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string look_up {
            get {
                return ResourceManager.GetString("look_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loose consist.
        /// </summary>
        public static string loose_consist {
            get {
                return ResourceManager.GetString("loose_consist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage addons.
        /// </summary>
        public static string manage_addons {
            get {
                return ResourceManager.GetString("manage_addons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage authors.
        /// </summary>
        public static string manage_authors {
            get {
                return ResourceManager.GetString("manage_authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage files.
        /// </summary>
        public static string manage_files {
            get {
                return ResourceManager.GetString("manage_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string management {
            get {
                return ResourceManager.GetString("management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum value.
        /// </summary>
        public static string maximum_value {
            get {
                return ResourceManager.GetString("maximum_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum value.
        /// </summary>
        public static string minimum_value {
            get {
                return ResourceManager.GetString("minimum_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string msg_error {
            get {
                return ResourceManager.GetString("msg_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your Train Simulator directory.
        /// </summary>
        public static string msg_first_time {
            get {
                return ResourceManager.GetString("msg_first_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string msg_message {
            get {
                return ResourceManager.GetString("msg_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No directory selected.
        /// </summary>
        public static string msg_no_directory_selected {
            get {
                return ResourceManager.GetString("msg_no_directory_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected path is invalid! (Check if it contains RailWorks.exe).
        /// </summary>
        public static string msg_ts_path_invalid {
            get {
                return ResourceManager.GetString("msg_ts_path_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid TS path is required to run this application. The application will now exit..
        /// </summary>
        public static string msg_ts_path_required {
            get {
                return ResourceManager.GetString("msg_ts_path_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string msg_warning {
            get {
                return ResourceManager.GetString("msg_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement vehicle.
        /// </summary>
        public static string new_vehicle {
            get {
                return ResourceManager.GetString("new_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string not_found {
            get {
                return ResourceManager.GetString("not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number list.
        /// </summary>
        public static string number_list {
            get {
                return ResourceManager.GetString("number_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old vehicle.
        /// </summary>
        public static string old_vehicle {
            get {
                return ResourceManager.GetString("old_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file.
        /// </summary>
        public static string open_file {
            get {
                return ResourceManager.GetString("open_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open scenario directory.
        /// </summary>
        public static string open_scenario_directory {
            get {
                return ResourceManager.GetString("open_scenario_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string path {
            get {
                return ResourceManager.GetString("path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preloads.
        /// </summary>
        public static string preloads {
            get {
                return ResourceManager.GetString("preloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Tracks.bin.
        /// </summary>
        public static string process_track_bin {
            get {
                return ResourceManager.GetString("process_track_bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Tracks.bin.
        /// </summary>
        public static string process_tracks_bin {
            get {
                return ResourceManager.GetString("process_tracks_bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Tracks.bin.
        /// </summary>
        public static string processing_tracks_bin {
            get {
                return ResourceManager.GetString("processing_tracks_bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string product {
            get {
                return ResourceManager.GetString("product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        public static string provider {
            get {
                return ResourceManager.GetString("provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading scenario files.
        /// </summary>
        public static string reading_scenario_files {
            get {
                return ResourceManager.GetString("reading_scenario_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repaint search directory.
        /// </summary>
        public static string repaint_search_dir {
            get {
                return ResourceManager.GetString("repaint_search_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repaint updater.
        /// </summary>
        public static string repaint_updater {
            get {
                return ResourceManager.GetString("repaint_updater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string replace {
            get {
                return ResourceManager.GetString("replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace all.
        /// </summary>
        public static string replace_all {
            get {
                return ResourceManager.GetString("replace_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with.
        /// </summary>
        public static string replace_with {
            get {
                return ResourceManager.GetString("replace_with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reversed.
        /// </summary>
        public static string reversed {
            get {
                return ResourceManager.GetString("reversed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolling stock.
        /// </summary>
        public static string rolling_stock {
            get {
                return ResourceManager.GetString("rolling_stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolling stock replacement.
        /// </summary>
        public static string rolling_stock_replacement {
            get {
                return ResourceManager.GetString("rolling_stock_replacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route.
        /// </summary>
        public static string route {
            get {
                return ResourceManager.GetString("route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route Visualizer.
        /// </summary>
        public static string route_visualizer {
            get {
                return ResourceManager.GetString("route_visualizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routes.
        /// </summary>
        public static string routes {
            get {
                return ResourceManager.GetString("routes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routes and scenarios.
        /// </summary>
        public static string routes_and_scenarios {
            get {
                return ResourceManager.GetString("routes_and_scenarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show list.
        /// </summary>
        public static string routes_show_list {
            get {
                return ResourceManager.GetString("routes_show_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RWP Packager.
        /// </summary>
        public static string rwp_packager {
            get {
                return ResourceManager.GetString("rwp_packager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlike some other programs that may try to generate an RWP file. This program actually creates a 1 to 1 .rwp file to that of Railworks. The RWP file format is actually just a normal .zip file, only with some bytes prefixed to beginning of the file. If you remove those bytes you can open it using any program. The reason you can open it using 7zip is that 7zip is very smart and treats it like an SFX but thats getting way to complicated. Those extra bytes at the beginning of the file are just the author&apos;s name [rest of string was truncated]&quot;;.
        /// </summary>
        public static string rwppackager_disclaimer {
            get {
                return ResourceManager.GetString("rwppackager_disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        public static string save_as {
            get {
                return ResourceManager.GetString("save_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save copy.
        /// </summary>
        public static string save_copy {
            get {
                return ResourceManager.GetString("save_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file.
        /// </summary>
        public static string save_file {
            get {
                return ResourceManager.GetString("save_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning .bin files.
        /// </summary>
        public static string scanning_bin_files {
            get {
                return ResourceManager.GetString("scanning_bin_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario.
        /// </summary>
        public static string scenario {
            get {
                return ResourceManager.GetString("scenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario downloader.
        /// </summary>
        public static string scenario_downloader {
            get {
                return ResourceManager.GetString("scenario_downloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenarios.
        /// </summary>
        public static string scenarios {
            get {
                return ResourceManager.GetString("scenarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View scenario list.
        /// </summary>
        public static string scenarios_show_list {
            get {
                return ResourceManager.GetString("scenarios_show_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script.
        /// </summary>
        public static string script {
            get {
                return ResourceManager.GetString("script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script component.
        /// </summary>
        public static string script_component {
            get {
                return ResourceManager.GetString("script_component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search vehicles.
        /// </summary>
        public static string search_vehicles {
            get {
                return ResourceManager.GetString("search_vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for addons.
        /// </summary>
        public static string searching_for_addons {
            get {
                return ResourceManager.GetString("searching_for_addons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Train Simulator directory.
        /// </summary>
        public static string select_ts_path {
            get {
                return ResourceManager.GetString("select_ts_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to serz.exe path.
        /// </summary>
        public static string serz_exe_path {
            get {
                return ResourceManager.GetString("serz_exe_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested display name:.
        /// </summary>
        public static string suggested_display_name {
            get {
                return ResourceManager.GetString("suggested_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested filename:.
        /// </summary>
        public static string suggested_filename {
            get {
                return ResourceManager.GetString("suggested_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template .bin.
        /// </summary>
        public static string template_bin {
            get {
                return ResourceManager.GetString("template_bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file which should be used as the default file for repaints. Its values will be used to update the repaint .bin files..
        /// </summary>
        public static string template_bin_explanation {
            get {
                return ResourceManager.GetString("template_bin_explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string test2 {
            get {
                return ResourceManager.GetString("test2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string test3 {
            get {
                return ResourceManager.GetString("test3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TgPcDx Viewer.
        /// </summary>
        public static string tgpcdx_viewer {
            get {
                return ResourceManager.GetString("tgpcdx_viewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TS path.
        /// </summary>
        public static string ts_path {
            get {
                return ResourceManager.GetString("ts_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn around.
        /// </summary>
        public static string turn_around_vehicle {
            get {
                return ResourceManager.GetString("turn_around_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown name.
        /// </summary>
        public static string unknown_name {
            get {
                return ResourceManager.GetString("unknown_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlicensed.
        /// </summary>
        public static string unlicensed {
            get {
                return ResourceManager.GetString("unlicensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unprotected.
        /// </summary>
        public static string unprotected {
            get {
                return ResourceManager.GetString("unprotected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use system language.
        /// </summary>
        public static string use_system_language {
            get {
                return ResourceManager.GetString("use_system_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naming hints: ND means &quot;No Driver&quot;, KI (german for AI) is for non player trains, ST is for &quot;Static&quot; vehicles. It&apos;s good practise to prefix your [Author] name in brackets. Example: [Author] Locomotive KI ND.
        /// </summary>
        public static string vehicle_naming_conventions {
            get {
                return ResourceManager.GetString("vehicle_naming_conventions", resourceCulture);
            }
        }
    }
}
